# Gradle Properties
	org.gradle.jvmargs=-Xmx6G

# Fabric Basic Properties
	# https://fabricmc.net/versions.html
	loader_version=0.19.3

# Global Dependencies
	# GCA (gugle-carpet-addition), compile-only for the menu-button compat mixin
	# https://modrinth.com/mod/gca
	gca_compile_version = v2.12.8+build.97

# Mod Properties
	mod_id=carpet-hfut-addition
	mod_name=Carpet HFUT Addition
	mod_version=1.5.0
	maven_group=dev.whisperlyric.carpet_hfut_addition
	archives_base_name=carpet-hfut-addition
